version: "3.9"

services:
  app:
    container_name: app
    image: app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    environment:
      ENV: production
      PORT: 8000
    build:
      context: ./backend
      dockerfile: Dockerfile
